### ISSUE TITLE
Build option to disable server log

### ISSUE THREAD

**Issue by Thatkookooguy** [SC5/sc5-styleguide#1007]
Hi! love this tool! The only problem I have is that it prints a lot to the console and I want the console to be clean and keep only my server's logs

is there a way to disable express logging for the server generated with `styleguide.generate`?

**Comment by kraftner** [comment]
Looks like it is [this line](https://github.com/SC5/sc5-styleguide/blob/7e9c8fa05c2a57c397d25ef7c34668600734f1bb/lib/server.js#L16), but I am not familiar with express or morgan. But would be a great feature. I hardly notice relevant errors and notices because the logs scroll them off screen.

**Comment by varya** [comment]
@Thatkookooguy Hi. Good proposal, thank you :-) This functionality has been implemented. Please, wait for this PR to be merged, and then for the following release.
https://github.com/SC5/sc5-styleguide/pull/1022

**Comment by Thatkookooguy** [comment]
@varya thanks!
