### ISSUE TITLE
Support for block comments

### ISSUE THREAD

**Issue by kchetan92** [SC5/sc5-styleguide#1014]
KSS supports block comments /**/, however sc5-styleguide wasn't able to parse it properly. Is this a bug?

**Comment by junaidrsd** [comment]
KSS supports block comments with only CSS. In order to use preprocessor it only supports inline comments. See this [section](https://github.com/kneath/kss/blob/master/SPEC.md) for details

**Comment by varya** [comment]
@kchetan92 If you still have a problem, please tell which syntax are you using, SASS, LESS, SCSS? If not, can we close the issue?

**Comment by kchetan92** [comment]
Thanks @varya , @junaidrsd . Your suggestion worked.
