### ISSUE TITLE
socket.io.js not found when styleguide is put on server

### ISSUE THREAD

**Issue by shanecarmody** [SC5/sc5-styleguide#1016]
Hey,

I don’t understand how `socket.io.js` is being referenced from `index.html`. I see these 3 lines at the bottom of the `index.html`:

``` html
<script src="/js/vendor.js"></script>
<script src="/js/app.js"></script>
<script src="/socket.io/socket.io.js"></script>
```

The `/js/` folder being referenced exists. The `/socket.io/` folder doesn’t. The styleguide works locally but not when I put the output folder on the server. I get this error:

`GET https://styleguide.proxi.tools/socket.io/socket.io.js 404 (Not Found)`

Is there something I need to do for installing `socket.io.js`?

**Comment by varya** [comment]
Are you sure you need socket.ip on server? Usually for public hosting styleguide is generated as a static website. If you do not use `server` option, the tool makes static style guide web site in the given folder. Look like I do this https://github.com/varya/varya.github.com/blob/develop/gulpfile.babel.js#L14 The result is here http://varya.me/styleguide/#/

Will this help you?
