### ISSUE TITLE
Allow to run multiple styleguide servers on different ports

### ISSUE THREAD

**Issue by juliami** [SC5/sc5-styleguide#1019]
Hi,

Is it possible to run multiple instances of sc5-styleguide on different ports?
I'm trying to generate 2 styleguides from one gulpfile (for two different themes in the app). So I registered 2 tasks:

```
gulp.task('styleguide:generateCore', function() {
  return gulp.src(scssCore)
     .pipe(styleguide.generate({
      server: true,      
      port: 4001,
     ...
    }))
    .pipe(gulp.dest(outputPathCore));
});

gulp.task('styleguide:generateChild', function() {
  return gulp.src(scssChild)
     .pipe(styleguide.generate({
      server: true,      
      port: 4002,
     ...
    }))
    .pipe(gulp.dest(outputPathChild));
});

```

They both work when called separately however when I use them both, I get 

`Express server listening on port 4002`

only and nothing is generated on port 4001.

Is there a way to have two instances running concurrently?

**Comment by varya** [comment]
Hi. There was no such feature. I've made a PR here #1021. Please wait a little bit for it to be merged, and for the upcoming version update.

**Comment by juliami** [comment]
Awesome, thank you.
