### ISSUE TITLE
sg-wrapper being ignored all over the project

### ISSUE THREAD

**Issue by marinho** [SC5/sc5-styleguide#1027]
I am a beginner in sc5-styleguide.

I've just created my own project copying the files `package.json` and `gulpfile.js` from **sc5-styleguide-tutorial**.

The styleguide is generated alright, including `sg-insert` and basic KSS support, but when `sg-wrapper` is completely ignored. No errors. Just the built styleguide renders the markup without wrapping HTML.

Funny that I couldn't see any difference between my code and **sc5-styleguide-tutorial**, but **sc5-styleguide-tutorial** generates `atoms.scss` correctly with sg-wrapper.

Here is the gist of `gulpfile.js` and one of my scss files:

- https://gist.github.com/marinho/46c50ad3a8e625c7063f060a85dea496

**Update**

I noticed that **sc5-stylesheet** version was quite outdated in **sc5-stylesheet-tutorial**. So I replaced my `gulp.js` by the example provided in the `README.md` file, as in the gist below. But the issue with `sg-wrapper` still happens.

- https://gist.github.com/marinho/7195c703b8ac6900d85d3ac4adf62384

**Comment by marinho** [comment]
Ooh, I found why: the KSS notation had a white space after the double slash comment just above `sg-wrapper`, as below:

```
// </header>
// <--- here
// sg-wrapper:
```

Curious that it seems KSS itself doesn't prohibit that, and the other spacings between other sections such as Title and Description, Stylesheet, etc. are fine and accepted.

To me, that seems a bug in **sc5-styleguide**.

**Comment by varya** [comment]
Thank you. This was a bug. It's fixed here https://github.com/SC5/sc5-styleguide/pull/1031 Please wait for the pull request to be merge and for the next release.
