### ISSUE TITLE
Live Preview (Web Socket) not updating styles on change

### ISSUE THREAD

**Issue by patriziosotgiu** [SC5/sc5-styleguide#1045]
I was able to successfully run the styleguide on my current project, but for some reason, the live preview feature is not working. 
I can see from the console log that the web socket is connecting and the server is running, but when I change a style or copy the page is not "refreshed."

The feature seems to work till the released version 0.3.47, but it breaks after upgrading to 1.0.0 and up. 

Is there any new setting or requirement to make the live preview work again?
I have tested it both with grunt and gulp.

(You guys did a great job by the way!)

**Comment by varya** [comment]
Hi. Sorry for this :-( Fixed and soon will be merged https://github.com/SC5/sc5-styleguide/pull/1055

**Comment by patriziosotgiu** [comment]
Hi @varya, that's great! Thank you so much for taking care of this.
