### ISSUE TITLE
Update Angular version

### ISSUE THREAD

**Issue by Lars-Weber** [SC5/sc5-styleguide#1072]
Hey,

we are currently getting a JS error breaking site functionality when displaying Angular components.

```
Uncaught TypeError: angular.module(...).info is not a function
    at angular-messages.js:275
...
```

An update of the Angular version from 1.5.5 to 1.6.3/1.6.4 (and subsequent modules angular-animate and angular-mocks) would be massively helpful.
Any chance this might happen soon?

The error appears since we moved our internal project to Angular version 1.6.3 and is most likely due to [these additions](https://github.com/angular/angular.js/commit/60e294cbd8f0c34ed03046778a0be3befc6b6982) introduced in Angular v1.6.3. The current difference in Angular versions seems to cause the problem.

**Comment by varya** [comment]
Hi. You can do it, if you have time. Please, provide a pull request (http://makeapullrequest.com/). If you need help with it, I'll be happy to give a hand.
Regarding implementation: It would be nice to provide an option for different versions of Angular. Maybe someone still needs old version.

**Comment by DanielaValero** [comment]
Hi @varya 

I will take over, you can assign the issue to me. 

However, making the version of angular configurable, might not be that straight forward. My first thought is to add it in the settings of the project, and let the project be built up with that specified version.

However, having defined the version to install of angular, is a decision that needs to happen before the project is installed, so bower knows which version should look for, and as well might require also to update some parts of the code base, so they are compatible with angular 1.6.x.

Therefore, my suggestion would be to do the work like this:

* Have a branch to handle the updates of angular, which could be published to npm with a @next or beta label or so. This way it would be available for people that need it
* Add deprecation warnings about breaking changes, so the users have time to fix whatever needs to be fixed
* Add a note about the update in the readme

once, it's safe, we could publish a major release, containing the change.

Does this make sense to you?

**Comment by varya** [comment]
Thanks @DanielaValero! I've sent you invitation to collaborators (I suppose I will be able to assign to you if you are a collaborator).
The plan you propose sounds solid, go ahead! You can make everything in your fork, and then do a PR. If you would like the origin repo to have a special branch for `@next` release, just let me know. Thanks again!
