### ISSUE TITLE
After 2.1.0 update - ERROR: Unable to exclude default styles 

### ISSUE THREAD

**Issue by dlangston** [SC5/sc5-styleguide#1128]
I was getting the same default style bug on clean build as described here [#1115](https://github.com/SC5/sc5-styleguide/issues/1115)

I updated to 2.1.0 because it is suppose to have a fix for this issue, however once I update to 2.1.0 I receive the following error when I run gulp -
`ERROR: Unable to exclude default styles `

I thought it might be related to the `includeDefaultStyles` but I am not using this and adding it to my gulp file doesn't seem to effect the outcome. Any help would be greatly appreciated because I am having to revert back to version 1.7.0 to not have the default style bug issue.

Also, I found that if you run gulp twice after a clean build the style bug seems to fix itself. Not sure why?

**Comment by junaidrsd** [comment]
@dlangston I think you're missing dist folder try running this task first

``` gulp build ```

**Comment by dlangston** [comment]
@junaidrsd Thanks for the reply. I haven't needed to run `gulp build` in the past, is this new? I currently don't have a build task in my gulp file so it fails if I run it. Up until now we have just installed SC5 via npm then ran the default gulp task, staticStyleguide. Thanks again for the help.

**Comment by junaidrsd** [comment]
This isn't new this task is a dependency to main tasks. Somehow it did not perform or dist folder might got deleted for some reason. I think I need to display meaningful error message.

**Comment by dlangston** [comment]
So what is the best way to make sure the dist folder is added?

**Comment by junaidrsd** [comment]
Dist folder is always there unless one delete it accidentally. I'm 100% occupied with other things otherwise there can be better ways to handle this situation.

**Comment by kasparsd** [comment]
I had the same issue with a fresh build and adding `includeDefaultStyles: true` to our config fixed it. This happens because this conditional:

https://github.com/SC5/sc5-styleguide/blob/b9787e3501ef1d712d43b98620ed4fdec0a7298d/lib/modules/common.js#L35

sets it to `false` if you don't specify it.

So the readme is actually wrong because the default is not `true`:

https://github.com/SC5/sc5-styleguide/blob/580b6d0868d29ad4511602b4eedbe1a9a7c67959/README.md#L229

**Comment by kasparsd** [comment]
Fix available in #1130.
