### ISSUE TITLE
 `libsass` bindings not found. Try reinstalling `node-sass`? (Windows)

### ISSUE THREAD

**Issue by liyuankui** [SC5/sc5-styleguide#284]
can't run the demo

**Comment by ferrybrouwer** [comment]
I have wrote a patch to solve this issue:
https://github.com/ferrybrouwer/node-sass-patch

**Comment by junaidrsd** [comment]
The problem can also be reproducible with node versions > 0.11.1 and is related to dlmanning/gulp-sass#185.

 I'm closing the issue but it can be reopened if needed
