### ISSUE TITLE
Use gulp-ruby-sass

### ISSUE THREAD

**Issue by aslansky** [SC5/sc5-styleguide#341]
If there is a chance to use [gulp-ruby-sass](/sindresorhus/gulp-ruby-sass) instead of gulp-sass? gulp-sass is hopelessly behind with features and can't compile a lot of sass third party libraries.

**Comment by varya** [comment]
https://github.com/SC5/sc5-styleguide/pull/386
But you need to wait for release

**Comment by jkarttunen** [comment]
You guys are in right track. :)

**Comment by jpbackman** [comment]
0.3.0 released, internal style preprocessing removed.
https://github.com/SC5/sc5-styleguide/releases/tag/0.3.0
