### ISSUE TITLE
'no socket connections' with socket.io v1.3.2

### ISSUE THREAD

**Issue by adam-beck** [SC5/sc5-styleguide#437]
When running the demo application I receive a `no socket connections` error in the browser. The `package.json` lists `sockets.io` as `"^1.2.1` which when the packages are installed socket.io version is bumped to `1.3.2`. If I explicity set the demo to use sockets.io `v1.2.1` I do not receive this error.

**Comment by jpbackman** [comment]
@adam-beck which version of sc5-styleguide are you using? We released 0.3.2 today, which addresses the socket connection issue (port is ignored). The root cause is in socket.io-client@1.3.2: https://github.com/Automattic/socket.io-client/issues/802

**Comment by adam-beck** [comment]
I was using a previous version.

**Comment by jpbackman** [comment]
The solution introduced in 0.3.2 is not perfect, as it assumes that users are connecting directly to the designated Express server port. Problems start when ports are forwarded.

**Comment by andreipopovici** [comment]
+1
Also having issues with forwarded ports.

**Comment by jpbackman** [comment]
@andreipopovici we released 0.3.3 yesterday with a downgraded version of `socket-io` (1.2.1) which resolves socket endpoint port correctly. 0.3.4 is the latest sc5-styleguide version (minor cli argument bug fixed), please update.

**Comment by andreipopovici** [comment]
Trying it as we speak :) Will update with progress.

**Comment by jpbackman** [comment]
0.3.4 works, we're running our demo site inside a Docker container, which forwards the internal port 3000 to something random like 49317 on the host machine, which again is mapped to 80 in nginx or apache.

http://demo.styleguide.sc5.io/

**Comment by andreipopovici** [comment]
Socket.io seems to work fine after the update. Thanks!

Heads-up: a small typo in the Gulp instructions (the comma after this line):

`var sass = require('gulp-sass'),`

**Comment by jpbackman** [comment]
@andreipopovici no problem, and thanks, well spotted. [Fixed it already](https://github.com/SC5/sc5-styleguide/pull/445), though. :)

**Comment by andreipopovici** [comment]
You need to slow down before these Internet wires catch fire :P
