### ISSUE TITLE
commonClass cli parameter is broken

### ISSUE THREAD

**Issue by alpadev** [SC5/sc5-styleguide#442]
Case:
Running *styleguide* with parameter *--commonClass "test"*
Expected:
Class *.test* is some how added to the CSS preview

**Comment by jpbackman** [comment]
Fixed in [PR#443](https://github.com/SC5/sc5-styleguide/pull/443) and released in [0.3.4](https://github.com/SC5/sc5-styleguide/releases/tag/0.3.4)
