### ISSUE TITLE
Color variable name printed wrong in 0.3.5

### ISSUE THREAD

**Issue by rallu** [SC5/sc5-styleguide#462]
This bug came with latest update. Didn't have it earlier.

So I have defined variable $color-white: #fffff; in sass. And then I'll print it out with KSS like:

```
// Colors
//
// Markup: <div style="background: {$modifiers}" class="styleguide-color">{$modifiers}</div>
//
// $color-white - white
//
// Styleguide 1.0
```

Now styleguide prints out following string "3px solid darken(#ffffff, 5%)" on top of color. There are several other colors with random text instead of name and some colors work fine.

It might be that if color is used somewhere and it is used in special way then name of it is getting some extra crap. 

Here is several examples of output I get instead of color name:
* lighten(2px solid lighten(#b0b0b1, 10%),20%)
* 2px solid 2px solid #e0e0e1
* 2px solid 2px solid 2px solid 2px solid 1px solid 1px solid 2px solid 2px solid 2px solid 2px solid 2px solid #0090f1

**Comment by jpbackman** [comment]
Fixed in 0.3.6 release (reverted gonzales parser to a known working version)
