### ISSUE TITLE
Getting TypeError when starting styleguide with gulp on Windows

### ISSUE THREAD

**Issue by mehtmehtsen** [SC5/sc5-styleguide#464]
I'm using sc5-styleguide with gulp on Win8.1 64bit.
When I start gulp in my project folder, I get the following error:
`TypeError: Cannot call method 'substr' of undefined`
The same error appears when I just go `gulp styleguide:generate`. 
When I empty the output-folder and try to generate the styleguide I only get a couple of css- and scss-files, but no html.
I already reinstalled everything in node_modules (no errors, no warnings) and emptied node's cache. I also tried the same project on OSX without a problem. 

I tried to track the problem with my humble javascript-knowledge by inserting `console.log("something")` at strategic points in styleguide.js and taking note of when it prints and when it doesn't, and I think I was successfull on line 189:

`...`
`console.log("test1"); // prints`
`Q.all([parseKSSPromise, parseVariablesPromise]).spread(function(sections, variables) {`
`console.log("test2"); // doesn't print`
`...`

I guess either something broken gets passed into q or q itself is broken.
Does somebody have a suggestion? Any help or insight would be greatly appreciated.

**Comment by jpbackman** [comment]
We'll look into this. There are some still some open issues with Windows, this might be related to the line breaks. Thanks for providing the TypeError; that's a good hint, since there's only one place in which `.substr()` is used in the code base. :)

**Comment by adrianschmidt** [comment]
I just want to chime in and say that I was experiencing the same problem after upgrading to 0.3.5. I reverted back to 0.2.17 while waiting for a fix.

I'm using Windows 8.1 Enterprise.

**Comment by jpbackman** [comment]
@mehtmehtsen @adrianschmidt have you by any chance had any issues with Windows CRLF (such as in issue #452)? I'll try to tackle the Windows issues asap, but I'm wondering if it's truly CRLF or perhaps some file encoding issue.

**Comment by jpbackman** [comment]
@mehtmehtsen @adrianschmidt 0.3.6 is released, can you check if it's working for you?

**Comment by mehtmehtsen** [comment]
@jpbackman just tried it, it works flawlessly now. thanks a lot. :-)

**Comment by jpbackman** [comment]
Excellent!

**Comment by adrianschmidt** [comment]
Yes, I have the same problem as issue #452 is describing, when using 0.3.4. But I'm not sure if it is caused by crlf or not.

I'll try 0.3.6 and report back!

**Comment by adrianschmidt** [comment]
0.3.6 resolved this issue for me too. Thanks for a really fast response!

Issue #452 still affects 0.3.6 though (I'll make a comment on that issue).
