### ISSUE TITLE
Sass Syntax Problem

### ISSUE THREAD

**Issue by optikfluffel** [SC5/sc5-styleguide#479]
Hey :)

I've stumbled across a little problem using `.sass` files and trying to copy your [color example](https://github.com/SC5/sc5-styleguide/blob/master/lib/app/sass/app.scss#L38-L49). I only got that to work only when I added the `;` which don't really belong there when using sass.
Do you know what's wrong there?

Thanks

**Comment by junaidrsd** [comment]
Hey,
Can't reproduce it or it might be fixed at some point.

**Comment by cyberixae** [comment]
I am closing this. Based on previous comment. Feel free to reopen the issue if it is still a problem.
