### ISSUE TITLE
How to Load JS file for Support of Modules?

### ISSUE THREAD

**Issue by khrome83** [SC5/sc5-styleguide#486]
How do I load in a JS file that is not used as part of Angular?

**Comment by khrome83** [comment]
I have tried to use the extraHead property to pass in a JS file. But this does not seem to interact with the components on the page. 

````
            extraHead: [
                '<script src="/js/head.js"></script>',
                '<script src="/js/main.js"></script>'
            ],
````

What is the best way for non-angular apps to include a JS file for the styleguide sections?

**Comment by khrome83** [comment]
Has anyone had any luck getting non-angular JavaScript exposed to a web component? To me this is Critical for us to adopt this as our StyleGuide generator. I work for General Motors and would love to push this forward as our internal standard.

**Comment by varya** [comment]
`extraHead` applies for a style-guide page itself and may not work with the components because each of them is encapsulated with shadow DOM.
Applying extra JS to a component is not implemented yet. We will create a task in the backlog to do this.

**Comment by vedrani** [comment]
+1 This would be great feature :)

**Comment by hannu** [comment]
As a workaround solution you can use `extraHead` and disable shadow DOM encapsulation with `disableEncapsulation` option.

**Comment by vedrani** [comment]
Thx :) @hannu

**Comment by azevedo-252** [comment]
:+1:

**Comment by patapron** [comment]
It does already?

**Comment by khrome83** [comment]
This was resolved be a release later in the year. Closing the issue.
