### ISSUE TITLE
Extend KSS Syntax

### ISSUE THREAD

**Issue by khrome83** [SC5/sc5-styleguide#487]
I find KSS Syntax very good, but with a few caveats

````
    // Block Name
    // 
    // Description OR Classes
    // 
    // markup:
    // markup code here
    // 
    // Styleguide 1.0
````

It would be ideal if we could have a section to identify modifiers, as well as document other things within the same block. Currently, I have to make a new block for the documentation, then a sub-section to show the code. This is fairly minor different, but it would make things cleaner. 

Additionally, it would be nice if we can define a specific description block that can output Markdown or HTML so we can provide links. This is something that needs to be done in markup as a example just to create cross-linking or showing outside dependencies.

**Comment by varya** [comment]
In the latest versions everything is possible with custom processors and custom KSS fields. You can find more info in this post: http://varya.me/en/posts/sc5-style-guide-next-level/
