### ISSUE TITLE
Incorrect `styleguide-applystyles` task for Grunt in the README

### ISSUE THREAD

**Issue by varya** [SC5/sc5-styleguide#491]
When running `grunt gulp:styleguide-applystyles`, there is an error `Warning: output is not defined Use --force to continue.`.

This is becaus ethe task is missing `var outputPath = 'output';` in the beginning. And the destionation should be `.pipe(gulp.dest(outputPath)`.

**Comment by ivnmaksimovic** [comment]
It is actually also missing a closing bracket in Gruntfile example. Destination should be `.pipe(gulp.dest(outputPath))`
