### ISSUE TITLE
Description section is rendered incorrectly

### ISSUE THREAD

**Issue by ctumolosus** [SC5/sc5-styleguide#492]
Given the following snippet:

```scss
// Lorem Ipsum
//
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae arcu non
// mauris efficitur pharetra sed a purus. Cras id sapien tortor. Nulla eget leo
// sed ligula molestie lobortis.
//
// Morbi ornare bibendum purus, non porta nibh hendrerit non. Praesent sed metus
// tincidunt, efficitur neque at, semper magna. Fusce vitae placerat ex. Cras
// rhoncus vehicula sodales. Aenean ac pulvinar augue, ut vulputate ex.
//
// Suspendisse gravida luctus accumsan. Curabitur dictum dolor ex, at suscipit
// ex rhoncus in.
//
// Styleguide 3.0
```

I would expect SC5 to render the description section as 3 paragraphs, but instead it combines them into a single paragraph.

Also, a lot of the markdown features are removed. For example, I can't use backticks to denote code or stars to denote emphasis.

**Comment by khrome83** [comment]
Yeah I find this frustrating as well. I experienced the same issue.

**Comment by kr3l** [comment]
+1

**Comment by cognivator** [comment]
+1

**Comment by ivnmaksimovic** [comment]
+1

**Comment by hannu** [comment]
This issue is fixed in the latest release, also markdown (as well as plain HTML) is now supported in the description blocks. Please notify me and open new issue if the issue still exists.
