### ISSUE TITLE
Cannot parse if statements and $var: $var; declarations

### ISSUE THREAD

**Issue by gazzwi86** [SC5/sc5-styleguide#496]
I am trying to parse neat and bourbon files and getting parse errors such as the following.  The code snippet is below - it looks like declaring variables as variables nor using if statements is well supported.  Maybe an issue with 

Error:
    Parsing error: Please check the validity of the block starting from line #118

    116 | @mixin flex-direction($value: row) {
    118*|     $value-2009: $value;
    119 |     $value-2011: $value;
    120 |     $direction: "normal";

Snippet:

    @mixin flex-direction($value: row) {

        $value-2009: $value;
        $value-2011: $value;
        $direction: "normal";

        @if $value == row {
            $value-2009: horizontal;
        }

        @elseif $value == "row-reverse" {
            $value-2009: horizontal;
            $direction: reverse;
        }

        @elseif $value == column {
            $value-2009: vertical;
        }

        @elseif $value == "column-reverse" {
            $value-2009: vertical;
            $direction: reverse;
        }

**Comment by hannu** [comment]
This is probably gonzales-pe issue not understanding the mixin. We'll have a look.

**Comment by junaidrsd** [comment]
This is related to issue #512.

**Comment by varya** [comment]
Which syntax is it: SCSS or SASS?

**Comment by gazzwi86** [comment]
@varya SCSS

**Comment by varya** [comment]
There is no such bug any more because we use new version of the Gonzales parser. But I also added a unit test to check this case in future versions.
https://github.com/SC5/sc5-styleguide/pull/954
