### ISSUE TITLE
Spaces before : and after make the variable not parsed by SC5

### ISSUE THREAD

**Issue by khrome83** [SC5/sc5-styleguide#498]
The following variables will not be parsed by SC5 correctly.

````
$white       : #FFFFFF;
$ghost       : #FAFAFA;
$snow        : #F9F9F9;
$vapor       : #F6F6F6;
$white-smoke : #F5F5F5;
$silver      : #EFEFEF;
$smoke       : #EEEEEE;
````

This will work - 

````
$white: #FFFFFF;
$ghost: #FAFAFA;
$snow: #F9F9F9;
$vapor: #F6F6F6;
$white-smoke: #F5F5F5;
$silver: #EFEFEF;
$smoke: #EEEEEE;
````

It is expected that SC5 should not care about the beautification of the CSS. A lot of plugins will do this automatically for developers, breaking the styleguide.

**Comment by hannu** [comment]
This is probably a gonzales-pe issue. We'll have a look.

**Comment by junaidrsd** [comment]
Gonzales-pe upgrade resolved the issue.

**Comment by khrome83** [comment]
Seems that the Gonzales package resolved the issue. Cool.
