### ISSUE TITLE
Sass variable parsing errors

### ISSUE THREAD

**Issue by marefr** [SC5/sc5-styleguide#512]
Parsing error: Please check the validity of the block starting from line #23

23* | $palette-color-1: #ffcf3c;

Gonzales PE version: 3.0.0-12
`$palette-color-1: #ffcf3c;`

Time to upgrade Gonzales PE?

**Comment by cyberixae** [comment]
Not sure if this is a Gonzales problem or not but we are looking into upgrading Gonzales again, so lets see if we can upgrade it and if this gets fixed in the process.

**Comment by junaidrsd** [comment]
Upgrading gonzales did not help. It is a valid SASS LESS syntax, gonzales should parse it. I've created this issue on gonzales <a href="https://github.com/tonyganch/gonzales-pe/issues/59">here</a>

**Comment by varya** [comment]
In SASS (not CSS) ending `;` is not allowed.

**Comment by junaidrsd** [comment]
According to #451 it's been fixed in Gonzales PE dev. Need to wait until next release i guess.
