### ISSUE TITLE
Use the Styleguide without HTML5 Mode for URLs

### ISSUE THREAD

**Issue by varya** [SC5/sc5-styleguide#534]
I would like to host the resultant styleguide site on `gh-pages`. This is a static hosting, it does not allow to run or tune server. So it is not possible to teach it to resolve all the URLs to `index.html`. This is why I would prefer to have the running Angular application in Hashbang Mode. So that the URLs it responds would be not `<server>/section/1` but `<server>/#section/1`.

Can we have an option in generator which switches off current HTML5 Mode for the URLs?

**Comment by cyberixae** [comment]
We were thinking about discarding the --output option but I think GitHub Pages is a good reason for keeping it around. We should still probably make the --output flag optional and keep the files in memory unless the user specifically wants to have them on disk. If we are still going to support outputting the files for static hosting we should revisit the singe-page app use case and check what works and what doesn't.

**Comment by hannu** [comment]
0.3.11 has now possibility to disable HTML5 history API wtih setting `disableHtml5Mode`.
