### ISSUE TITLE
app.css contains style that breaks HTML lists in Overview page

### ISSUE THREAD

**Issue by ejwaibel** [SC5/sc5-styleguide#559]
I noticed that my Overview page (which is generated from a README.md file) didn't have bullets or numbers for my lists. After investigating the CSS, I noticed that in the styleguide/css/app.css file, the `.sg` style has `display: block`. As soon as I remove the `display: block` my bullets and numbers show up correctly.

**Comment by hannu** [comment]
Thanks! This will be fixed in the next release.
