### ISSUE TITLE
.css files must be renamed to .scss else TypeError: undefined is not a function (0.3.9)

### ISSUE THREAD

**Issue by andrewjbaker** [SC5/sc5-styleguide#563]
We've had to rename our CSS files from .css to .scss in order for SC5 Styleguide generation to succeed without error.

Interestingly, you can rename file.css to file.scss but continue to reference file.css in the gulpfile.js and generation succeeds.

gulp.task('styleguide:generate', function() {
  return gulp.src('file.css')
    .pipe(/* ... */)
    // ...

**Comment by andrewjbaker** [comment]
Note that Styleguide sections aren't generated if the reference to file.css in the gulpfile.js is not updated.

**Comment by hannu** [comment]
This should be fixed in 0.3.10. Please re-open the issue if the problem still occurs.

**Comment by andrewjbaker** [comment]
Thank you; tested it and it is. (thumbsup)
