### ISSUE TITLE
Problems with finding imported scss variables

### ISSUE THREAD

**Issue by cyberixae** [SC5/sc5-styleguide#567]
reproduction:
1. create a variables.scss files with at least one variable
2. create a definitions.scss file that uses one of the variables
3. creata a main.scss file that imports first variables.scss and then definitions.scss
4. create a styleguide from main.scss

what happens: something fails to find the variable definitions and style guide generation fails
what should happen: style guide generation should not fail

**Comment by hannu** [comment]
`styleguide.generate()` does not compile SCSS files and thus is not able to follow import references. You need to pass `*.scss` to that function. On the other hand, compiled sources are passed to `styleguide.applyStyles()` so in that case passing only the main.scss is ok.

Could you give me example of file selectors that are passed in `gulp.src()` to `generate()` and `applyStyles()`?

**Comment by cyberixae** [comment]
Check out https://github.com/SC5/sc5-styleguide-tutorial/
I had to add extra imports to src/styles/atoms.scss and src/styles/helpers.scss to get it working.

**Comment by cyberixae** [comment]
The following error message gets printed to the console.
[10:43:19] Starting 'staticStyleguide:applystyles'...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: unbound variable $eg-default-fonts

**Comment by hannu** [comment]
The problem was just a typo in `scss` task, not styleguide related issue. Fixed in https://github.com/SC5/sc5-styleguide-tutorial/pull/9
