### ISSUE TITLE
Menus sometimes display HTML notation

### ISSUE THREAD

**Issue by cyberixae** [SC5/sc5-styleguide#569]
After using the style guide generator for a while it sometimes breaks and the menus start showing HTML notation (see the screenshot below). After restarting the style guide generator everything returns to normal.

![image](https://cloud.githubusercontent.com/assets/1158275/7084213/7d85dff2-df73-11e4-9794-912e4eb7d246.png)

**Comment by cyberixae** [comment]
The issue can be reproduced by loading the page a few times while the style guide is being built. The problem remains after the build is completed so it is not simply about looking at an incomplete version. Perhaps the broken version is cached somewhere and the actual working version never replaces the broken one in the cache.

**Comment by milkshoes** [comment]
I am experiencing this very same issue. I've tried everything and the only thing I find to work as this point is restarting the server. I currently close the server and re-run "npm run demo" to get the ui to be correct again.

**Comment by milkshoes** [comment]
I feel like this needs to be addressed sooner than later since this is really a productivity killer in the sense that one needs to stop and start the server to see the ui correctly.

**Comment by hannu** [comment]
I will have a look at this next.

**Comment by milkshoes** [comment]
Awesome. Thanks! Also here is a screen shot verifying my same behavior as described cyberixae.

![sc5_watcher_update_header_issue_2015_01](https://cloud.githubusercontent.com/assets/2328121/7140178/f973e4b6-e297-11e4-9d23-1cb80769df41.png)
