### ISSUE TITLE
Vertical navigation menu is not available anymore in the latest version

### ISSUE THREAD

**Issue by frankieloscavio** [SC5/sc5-styleguide#583]
Please forgive me if I'm missing a setting, configuration parameter or missing something else more obvious, but why does your public SC5 demo have a left vertical sidebar layout and then the demo for users that run locally have a top horizontal layout? I'm guessing everything configurable completely, but in a way it's kind of weird to see your demo and then get a slightly different demo after running. Personally, I think your public demo is much cleaner with the left vertical sidebar navigation and was hoping to see a clone of this after my first run.  Now I'm suspecting I have to do extra templating and layout to get to where I expected to be based on your public demo. Not hard, but different than what I had expected as the initial output. Screen shots are attached to make it clear what i'm referring to.

Thanks for your time and patience! Again, I'm sorry if this is obvious but I thought it was important enough to bring up as an issue.

PUBLIC DEMO:
![public_sc5_demo_navigation](https://cloud.githubusercontent.com/assets/2328121/7181818/4c8bedfe-e41b-11e4-8cf9-5bf6bdfdabc5.png)

LOCAL NPM DEMO:
![local_sc5_npm_demo_navigation](https://cloud.githubusercontent.com/assets/2328121/7181817/4c89ff3a-e41b-11e4-834c-d63f46820ffd.png)

**Comment by hannu** [comment]
The public demo is based on 0.3.6 (yes, it needs to be updated) and the horizontal menu was introduced in 0.3.9. Some huge style guides had performance problems since rendering the whole main section was enforced. With the horizontal navigation you can navigate directly to desired sub-section. We also wanted to give more horizontal space for the actual content. It's true that horizontal menu does not work well if you have many main section.

In the ideal use-case this should be configurable or customisable.

**Comment by justinnichols** [comment]
+1

I agree, making this a configurable option is very desirable.  I'm unsure how much of a design/implementation impact it is, but you could solve the issue for the left-menu by introducing flyouts on hover similarly to what is done with the horizontal menu.

**Comment by milkshoes** [comment]
+1 

I would love to be able to have an option to use the left menu vertical navigation. To me it was part of my decision making process when searching what living style-guide to use. Granted it wasn't the #1 decision, but it was a part of the process to use your really awesome product. Really the amount of work you have done, the quality of the product and the way you are so responsive is worth of donations! Of which I'd be happy to contribute. If may have your pay pal or method of donation, I will contribute. A sincere thank you for what you are doing.

**Comment by hannu** [comment]
Public demo is now updated to 0.3.13. I updated the title of this issue.

**Comment by iegik** [comment]
+1 For vertical Styleguide navigation
- https://www.google.com/design/spec/ (Vertical)
- http://primercss.io/scaffolding/ (Vertical)
- http://www.getmdl.io/ (Horizontal)
- http://bootstrapdocs.com/v3.3.5/docs/css/ (Mixed)
- https://material.angularjs.org/latest/ (Vertical)

**Comment by miukimiu** [comment]
It would be great to have a vertical nav. Hope you can create this new feature.

**Comment by junaidrsd** [comment]
Since vertical nav feature has been reintroduced in 0.3.46 with configureable option, I'm closing this issue.
