### ISSUE TITLE
How to serve images?

### ISSUE THREAD

**Issue by easingthemes** [SC5/sc5-styleguide#584]
Hi,
I'm using Grunt version, and everything is working fine, 
but I can't figure out how to see images?
Images are referenced from css `'../images/image.jpg'`.
```
http://localhost:9000/images/image.jpg 404 (Not Found)
```
Thanks.

**Comment by easingthemes** [comment]
I just copied `images` directory in styleguide root dir, and it worked.

**Comment by hannu** [comment]
Images, fonts and other static assets should be copied to style guide output folder to make them accessible in the style guide. It is recommended to create a gulp or grunt task to do the copying always when the style guide is generated.

I just improved documentation related to assets: https://github.com/SC5/sc5-styleguide/pull/585/files
