### ISSUE TITLE
Include scripts for components in styleguide

### ISSUE THREAD

**Issue by brp-nylin** [SC5/sc5-styleguide#601]
You can include additional styles for your styleguide "components", is there a way of including scripts as well? I have a couple of components that uses bootstrap scripts to work and display properly, but I can't seem to find a way to include the script related to the component, for example the accordion script.

**Comment by rhinocoders** [comment]
Looking for this option as well

**Comment by varya** [comment]
+1

**Comment by hannu** [comment]
As a workaround solution it is possible to include scripts using `extraHead` option. However shadowDOM should be disable or otherwise scripts are not able to modify content inside the shadowDOM (Set `disableEncapsulation: true`)

**Comment by Grienauer** [comment]
Is there any progress with a solution where we don't need `disableEncapsulation: true`?
Or is this not possible/will this never happen...

Thx for the Info!

**Comment by varya** [comment]
Possible now.
Please, read this http://varya.me/en/posts/sc5-styleguide-for-smallers/ and this http://varya.me/en/posts/sc5-style-guide-next-level/
