### ISSUE TITLE
Body tag selector definitions are being applied, instead it shows the browser's default font

### ISSUE THREAD

**Issue by nirmalkc** [SC5/sc5-styleguide#623]
I have defined some styles for the body tag as shown below. Seems like it is not taken by the shadow dom which you are using to render the user defined styles in the styleguide.

body {
font-family: $base-font-family;
font-size: $theme-font-size-base;
color: $theme-pcolor-black;
}

Basically, I would want a custom font and its properties to be used across my application, but in the styleguide it shows the browser's default font. 

Do you have any solution to address this?

**Comment by hannu** [comment]
Unfortunately it's impossibly to apply `body` and `head` inside the shadow DOM. As a workaround solution I would suggest you to create `.body` class and apply that using `commonClass` option.

See https://github.com/SC5/sc5-styleguide#html-and-body-styles

**Comment by nirmalkc** [comment]
That worked. Thank :)

**Comment by CGTS** [comment]
I'm running into this same issue but needed further clarification. I've added the commonClass and it's adding the class to the wrapper, but no styles are being applied. Right now the style is defined in my scss file `html, .sg-html {...}`. Do I need to define this somewhere else?
