### ISSUE TITLE
Difference between npm installed project and cloned github project?

### ISSUE THREAD

**Issue by CGTS** [SC5/sc5-styleguide#625]
When pulling down the project from npmjs.org it includes one gulp file 'demo-gulpfile.js' but the git clone includes 3 gulp files one being 'gulpfile.js' (which I would expect to see normally).

Which one should I be using when starting a new project? and is there a way to pull down a project that only contains the files necessary for a project using gulp without the demo site?

**Comment by hannu** [comment]
You should install project with `npm install sc5-styleguide`. The NPM contain only files that are necessary to make the style guide work. The demo site is actually generated from the style guide styles that are needed for the UI so there isn't separate demo site inside the package. It's true that `demo-gulpfile.js` is not needed in the production use but all other files are.

**Comment by CGTS** [comment]
Thanks.
