### ISSUE TITLE
Add stylus support

### ISSUE THREAD

**Issue by danielditgens** [SC5/sc5-styleguide#663]
Please add stylus support to your project.

**Comment by agilevolunteer** [comment]
+1

**Comment by chodorowicz** [comment]
+1

**Comment by argyleink** [comment]
+1

**Comment by varya** [comment]
The stylus support is not possible until there happens a parser which can parse Stylus code. This will only possible with the next major version of Stylus (currently there are some  things in syntax which do not allow to write a good parser). We are in contact with the Stylus team and will support it as soon as it become technically possible.

**Comment by varya** [comment]
@kizu Hi Roma! Could you give update about the Stylus syntax. (Just checking that the status is still the same as we discussed previously) Thanks!

**Comment by iamstarkov** [comment]
I think it will also possible with new version of postcss with custom parsers

**Comment by kizu** [comment]
Sadly, the status is the same. We're going to provide a way to get the parsed Stylus AST or something, probaly only when we'd get to 1.0.0, but no exact ETA. For simple use cases it is possible to use custom parsers like the postcss' one, but they would always perform badly in a lot of cases, as Stylus have a rather complicated syntax in some places.

**Comment by kizu** [comment]
@varya btw, @Panya told me there _is_ a way now to use Stylus' own parser from 0.x versions, but it won't contain all the tokens, for example there won't be inline comments, but there'll be block level comments which are used for sc5-styleguide, so you could use this way I guess? Look at [this example](https://gist.github.com/kizu/41f40714ea533ee1f876) to see how to use the Stylus' parser and how its current ast looks like. Would it be enough to make sc5-styleguide to work with Stylus?
