### ISSUE TITLE
Special characters in page title

### ISSUE THREAD

**Issue by Lazze2k5** [SC5/sc5-styleguide#664]
Main sections with special characters such as &, " and the Swedish å, ä and ö is shown as HTML characters in the page title.

Example:
// Färger & "typsnitt"
//
// Description...
//
// Styleguide 1.0

Shows correctly on the page but as "1 F&amp;#xE4;rger &amp;amp; &amp;qout;typsnitt&amp;quot; - Styleguide" in the page title when I'm browsing that section.

**Comment by Lazze2k5** [comment]
Just updated my project against the dev branch and the issue seems to be fixed, thanks for being so quick!

**Comment by hannu** [comment]
This issues is now fixed also in the NPM package (0.3.23)
