### ISSUE TITLE
overview.html 404 (Not Found)

### ISSUE THREAD

**Issue by iegik** [SC5/sc5-styleguide#690]
I`ve added styleguide-generate into my [gruntfile](https://github.com/iegik/chicagogaragedoors/blob/master/Gruntfile.js#L251) as shown in README, but  got 404 on /overview.html and /socket.io/socket.io.js

**Comment by iegik** [comment]
/socket.io/ client can be fetched here: https://github.com/Automattic/socket.io-client.git

**Comment by everlastin** [comment]
@iegik I'm getting the same error via grunt. Were you able to solve the issue and if you did then can you explain how?

**Comment by iegik** [comment]
In the documentation there is nothing says about Socket.IO dependency.
About the overflow.html - it seems to be generated by https://github.com/SC5/sc5-styleguide#documenting-syntax ...
I did not complete configuration jet.

**Comment by mindmelting** [comment]
I am also getting a 404 on overview.html using gulp

**Comment by varya** [comment]
@iegik Did I understand correctly that the problem was missing `overviewPath` in the config? I fixed the Grunt example in the documentation https://github.com/SC5/sc5-styleguide/pull/732

**Comment by mindmelting** [comment]
@varya adding `overviewPath` worked for me.
