### ISSUE TITLE
How to use html files as markup?

### ISSUE THREAD

**Issue by rryter** [SC5/sc5-styleguide#701]
Hit there

I'm probably missing something, I can not get the "Markup: file.html" syntax to work, it always displays the text instead of the html from the file.

```
// Tabs
//
// markup: tabs.html
//
// Styleguide 2.1
```

The spec says: 
>Instead of using inline HTML markup, you could point at a separate file that contains your HTML. kss-node supports either a plain *.html file or a Handlebars *.hbs file. The kss-node generator will search for the markup file in any of the --source folders.

Does that mean that I should place the .html file where my sass files are? And then change gulp.src?
Because when I do that the server fails to start.

This is how my generate task currently looks like (coffeescript):
```
  gulp.src(['./app/styles/**/*.scss', '!./app/styles/helper/*.scss'])
      .pipe(plugins.styleguide.generate(
          title: 'localsearch.ch Styleguide'
          server: true
          port: 3002
          styleVariables: './app/styles/settings/variables.scss'
          rootPath: 'styleguide'
          overviewPath: 'README.md'))
      .pipe gulp.dest('styleguide')
```

If anyone could shed some light into this I would appreciate it. I'll also gladly write the docs for this as soon as I know how it's supposed to work.

Many thanks.

**Comment by g12n** [comment]
I am currently having exactly the same problem

**Comment by H1D** [comment]
Same here! If I add html as a source it says `Syntax "html" is not supported yet, sorry`

**Comment by varya** [comment]
Hi. Inserting html file is not a part of KSS parser, so it did not appear in the SC5 styleguide when we updated it to KSS 2.0. But I implemented this feature as well https://github.com/SC5/sc5-styleguide/pull/721 You need to wait for the PR to be merged and released.

I also created a "refactoring" issue which would let us avoid such situations. https://github.com/SC5/sc5-styleguide/issues/722
