### ISSUE TITLE
Sections aren't generated

### ISSUE THREAD

**Issue by H1D** [SC5/sc5-styleguide#711]
Hi! Trying to getting started, but something seems broken.

test file I use – https://gist.github.com/H1D/1e35e4e461cd612f9103
and a command: `styleguide --kss-source styles.css --style-source styles.css --output styleguide --watch --server`

I expecting simple style guide with one section, but resulting style guide has no sections:
![image](https://cloud.githubusercontent.com/assets/697625/8727695/c5952a24-2be9-11e5-89a1-81c43de26102.png)

P.S. Console output seems OK:
![image](https://cloud.githubusercontent.com/assets/697625/8727682/a96b3c08-2be9-11e5-8a93-e118a51989f7.png)

**Comment by homertherefore** [comment]
I've been working to leverage this project recently, and found the use of the 'Styleguide' to be explicitly limited, but believe it's due to kss itself.  In the style file you've linked, try using 'Styleguide 1.x.x' without a colon, that should do the trick I believe.

**Comment by H1D** [comment]
@homertherefore yep thx!

**Comment by sascha-egerer** [comment]
@H1D please close the issue
