### ISSUE TITLE
After forked, dist file not generated after `npm install`

### ISSUE THREAD

**Issue by erem-ifg** [SC5/sc5-styleguide#734]
Hi,

After I forked your repository, `npm install` won't generate a `dist` directory (where I get the index.html file from).
I did not make any change:
https://github.com/ifeelgoods/sc5-styleguide/tree/0.3.27 = https://github.com/SC5/sc5-styleguide/tree/0.3.27 == 282abb17b61248c95be8d432cc8e907e6cdb0371

I referenced it in my package.json:
```
{
    ...
    "sc5-styleguide": "https://github.com/ifeelgoods/sc5-styleguide.git#~0.3.27"
    ...
}
```

`$ ls -l node_modules/sc5-styleguide/lib`
```
app
demo
modules
overview.md
server.js
styleguide.js
```

Is there something I'm missing?
Thanks for your help.

**Comment by varya** [comment]
Hi @erem-ifg. I got the same. I will try to find out what's wrong today.

**Comment by varya** [comment]
Note: the damage happend in this commit https://github.com/SC5/sc5-styleguide/commit/7750a336fc0b97636bc5096dbcf9aca1a2780510
