### ISSUE TITLE
AppRoot question

### ISSUE THREAD

**Issue by CoralSilver** [SC5/sc5-styleguide#735]
I don't understand the appRoot build option.  I'm running the styleguide locally with gulp, setting the rootPath to 'styleguide'.  

Ideally, I'd like to be able to run the styleguide locally building from my project, push it (project and styleguide) to gh-pages, and have it accessible from there. Is that possible?

If I set the appRoot to 'styleguide' in addition to setting the rootPath, it doesn't load locally.  Are both appRoot and rootPath supposed to be set to run on a server or can only appRoot be set?  I've tried just setting appRoot, but it doesn't resolve the file paths correctly, either.

I apologize, but I don't understand what this means:

>When using the build as a subdirectory of your application, tune your server to resolve all the paths to that subdirectory. This allows Angular to deal with the routing. However, the static files should be resolved as they are stored.

Can this be done with github gh-pages, or would it have to be hosted on another server?

**Comment by varya** [comment]
Hi. You will need this option if you host the result of the build somewhere in a folder. I described the case when telling how to run the Styleguide on gh-pages http://varya.me/en/posts/sc5-styleguide-for-smallers/#providing-the-approot-parameter-
