### ISSUE TITLE
Sass variable interpolation breaks parser

### ISSUE THREAD

**Issue by anttisalo** [SC5/sc5-styleguide#753]
On styleguide generation an error is thrown:

Parsing error: Please check validity of the block starting from line #247

246 | @mixin placeholderColor($element, $color)
247*| 	#{$element}::-webkit-input-placeholder
248 | 		color: $color

Seems that the parser does not support sass variable interpolation.

**Comment by varya** [comment]
Related issue https://github.com/tonyganch/gonzales-pe/issues/86

**Comment by varya** [comment]
Actually, this is duplicate. https://github.com/SC5/sc5-styleguide/issues/518
Subscribe that bug to keep updated.
