### ISSUE TITLE
!optional flag

### ISSUE THREAD

**Issue by babsgosgens** [SC5/sc5-styleguide#757]
Consider the following scss:

.foo { color: Red; }
.bar { @extend .foo; }
.foobar { @extend .foo !optional; }

The !optional flag is tripping the style guide parser:

Parsing error: Please check validity of the block starting from line #62

60 | .foo { color: Red; }
61 | .bar { @extend .foo; }
62*| .foobar { @extend .foo !optional; }

**Comment by varya** [comment]
We can try PostCSS parser instead of Gonzales for SCSS. Maybe this will fix. The related issue #767.

**Comment by varya** [comment]
Before it's fixed, you can use `/* styleguide:ignore:start */` and `/* styleguide:ignore:end */` magic comments to wrapped the erroring code.

**Comment by babsgosgens** [comment]
Thank you
