### ISSUE TITLE
Generated markdown table tags do not have "sg" class or any styles

### ISSUE THREAD

**Issue by nathanjosiah** [SC5/sc5-styleguide#783]
I am adding a table using markdown:

```sass
/*
	Table Test

	Heading1 | Heading2
	-------: | --------
	Item 1   | Things are here
	Item 2   | More exciting things
	Item 3   | Yet another thing

	Styleguide 5.3
*/
```

The generated markup does not contain the `sg` class on the table:

```html
<table>
	<thead>
		<tr>
			<th style="text-align:right">Heading1</th>
			<th>Heading2</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td style="text-align:right">Item 1</td>
			<td>Things are here</td>
		</tr>
		<tr>
			<td style="text-align:right">Item 2</td>
			<td>More exciting things</td>
		</tr>
		<tr>
			<td style="text-align:right">Item 3</td>
			<td>Yet another thing</td>
		</tr>
	</tbody>
</table>
```

But it also doesn't look like there are any default style applied to it:

![table](https://cloud.githubusercontent.com/assets/665104/9744533/489abc48-5621-11e5-8e0d-6361412ad209.PNG)

Perhaps this feature of markdown was forgotten?

For consistency, it would be nice to have the `sg` class here as the rest of the rendered markdown already contains the `sg` class.

**Comment by shekhardesigner** [comment]
I see the tables are still not applied styles while sg class is added. Do you have any plans to add table styles?
