### ISSUE TITLE
sg-insert with modifiers

### ISSUE THREAD

**Issue by Grienauer** [SC5/sc5-styleguide#784]
It would be great to add a class or the ability to define that all modifiers should be loaded with an inserted component.

Now, if I use <sg-insert>x.x.xx</sg-insert> only the default item is included, but it would be great to display the item with all Modifiers or have the ability to add the modifier class to it.

thx fot the great tool!

**Comment by kr3l** [comment]
+1

**Comment by criz** [comment]
+1

**Comment by kraftner** [comment]
+1

**Comment by kraftner** [comment]
As we already kind of [have a syntax for targeting modifier versions](http://demo.styleguide.sc5.io/section/1.1-1/fullscreen) when opening them in fullscreen mode I suggest this syntax for this feature:

<sg-insert>1.1-1</sg-insert>

**Comment by Grienauer** [comment]
thx!
