### ISSUE TITLE
SVG Sprite

### ISSUE THREAD

**Issue by bubbleheadinc** [SC5/sc5-styleguide#819]
@varya Follow up on Twitter convo...

I use SVG sprites for icons for my project, but I don't see a way to inject code into the body of the styleguide, so that the icons can be used in examples.

I generate the SVG sprite via gulp and then use ng-include to output the sprite just inside the body tag:

```
<body ng-app="app" ng-controller="AppController">
   <ng-include src="'images/svg-sprite.svg'">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display:none">
       <symbol id="myLogo">
           <polygon fill="#000000" points="65,20 158,800 28,22 "></polygon>
        </symbol>
         ... more symbol icons ...
      </svg>
   </ng-include> 
... 
</body>
```

So I can then use each icon with the <use> element anywhere on my pages, like this:
```
<svg class="b-icon--svg  b-icon--wSpace">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#myLogo"></use>
</svg>
```

Is there a way I can get the sprite to be available in the styleguide?

Thanks!

**Comment by varya** [comment]
Hi.
I think in some of CSS (SCSS, or what you use) you can provide comments describing these icons. Something like:

```
// Icons
//
// Styleguide 1

// Logo
//
// markup:
// <svg class="b-icon--svg  b-icon--wSpace">
//      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#myLogo"></use>
// </svg>
//
// Styleguide 1.1
```
Will this work?

**Comment by bubbleheadinc** [comment]
Sure. That would work for showing the icon in an example, but the icon won't load without the sprite in the body. How can I get the sprite into the body of the generated styleguide? Thanks!

**Comment by varya** [comment]
@bubbleheadinc An option to add custom HTML was added in this pull request #849. You should expect the new version to be able to use it.
