### ISSUE TITLE
How do I use sc5 in a automatisation process?

### ISSUE THREAD

**Issue by eystein** [SC5/sc5-styleguide#826]
This might be the wrong place to ask, but I can't find the answer anywhere.

When installing sc5 through `npm install sc5-styleguide --save-dev` it is installed inside the node_modules directory. Which I'm then supposed to `cd` into and run from there? The demo-output is also created in there. 

Should I not be running and outputting it _outside_ of the node_modules folder?
It's not even producing a package.json file in root? 

Or do I treat sc5 as a gulp module, and use it in my own custom workflow?

Best regards,
Eystein

**Comment by hannu** [comment]
sc5-styleguide is meant to be used as gulp module. You need to create a new `gulpfile.js` to your project root directly. There is a example of the minimal configuration in the README file which you can use as a starting point (https://github.com/SC5/sc5-styleguide#with-gulp).

This is not styleguide related but could help: `--save-dev` adds dependency to `package.json`only if you already have the `package.json`. It does not create a new file.

Please re-open this ticket you still have problems

**Comment by eystein** [comment]
That explains what I was wondering about. Thank you!
