### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Indomian** [SC5/sc5-styleguide#828]
Hello,
please update dependencies **pleeease** and **gulp-pleeease** to latest, so it begin working on Node4.x+

Before updating i kept getting error:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: css.walkRules is not a function

```

Fast investigation shows problem in **pleeease** and **gulp-pleeease**

**Comment by ctumolosus** [comment]
Also, allows integration with Node 4 :+1:

**Comment by track0x1** [comment]
:+1:

**Comment by gisu** [comment]
👍needed

**Comment by wojciech-slowacki-itv** [comment]
Would greatly appreciate it, had to remove styleguide from npm dependencies in our project, because it made the build fail.
