### ISSUE TITLE
SASS interpolation error on properties.

### ISSUE THREAD

**Issue by MakhBeth** [SC5/sc5-styleguide#831]
Hi all,
I get an error when I try to run something like that:

```SCSS
$direction: left;
.element {
  margin-#{$direction}: 10px;
}
```

```
Generating style guide to output dir: styleguide
Parsing error: Please check validity of the block starting from line #3

1 | $direction: left;
2 | .element {
3*|   margin-#{$direction}: 10px;
4 | }

Syntax: scss
Gonzales PE version: 3.0.0-31
```
The code is correct in Sass syntax and will compile well. 

I get the error only if the interpolation is on property, everything works fine if the interpolation is in the rule declaration or on the value side.

Any suggestion?

**Comment by varya** [comment]
Hi. This is invalid SASS, you can check it here http://sassmeister.com/ (choose SASS in options). The Result is `Invalid CSS after "left": expected expression (e.g. 1px, bold), was ";"`.

You may mix it with SCSS. If you meant to use SCSS not SASS, change the extension of your files to `*.scss`, or tell the tool that by `sass` you mean `scss` with `parser` parameter:

```
return gulp.src(['lib/app/sass/**/*.sass'])
  .pipe(styleguide.generate({
    title: 'My project',
    ...
    parsers: {
      'sass': 'scss'
    }
  })
```

You can find this option described in README: https://github.com/SC5/sc5-styleguide#build-options

**Comment by colinkahn** [comment]
I'm trying something similar with `scss` and getting the same issue. If I try the example posted by @MakhBeth in an `.scss` I get the same error he posted.
