### ISSUE TITLE
Viewing generated styleguide

### ISSUE THREAD

**Issue by devonatdomandtom** [SC5/sc5-styleguide#838]
This may not be the right place to ask...but where do I navigate to see the generated styleguide?

Using the plugin with grunt as described here: https://github.com/SC5/sc5-styleguide#with-grunt

Here's the relevant part of my grunt config
```javascript
gulp: {
      'styleguide-generate': function() {
          var outputPath = 'styleguide';
          return gulp.src(['<%= config.app %>/styles/main.scss'])
              .pipe(styleguide.generate({
                  title: 'CNN Pol Quiz Styleguide',
                  server: true,
                  rootPath: outputPath,
                  overviewPath: 'README.md'
              }))
              .pipe(gulp.dest(outputPath));
      },
      'styleguide-applystyles': function() {
          gulp.src('<%= config.app %>/styles/main.scss')
              .pipe(styleguide.applyStyles())
              .pipe(gulp.dest('outputPath'));
      }
    },
```
I notice when I run `grunt gulp:styleguide-generate` the terminal output is as follows
```
Running "gulp:styleguide-generate" (gulp) task
Express server listening on port 3000

Done, without errors.


Execution Time (2015-11-20 14:14:50 UTC)
loading tasks              1.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 52%
loading grunt-gulp        154ms  ▇▇▇▇▇▇ 5%
gulp:styleguide-generate   1.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 43%
Total 3.2s
```

My guess would be http://localhost:3000/styleguide, but I get no response. Hopefully I'm just neglecting something really simple.

**Comment by kraftner** [comment]
If you look closely at the docs you see that at the end there is `watch` which causes the grunt task to keep running.

    grunt.registerTask('default', ['gulp:styleguide-generate', 'gulp:styleguide-applystyles', 'watch']);`

Otherwise the server is started but immediately closed again. If you do not want this on the `default` task just call it something different, e.g. `styleguide-server`

    grunt.registerTask( 'styleguide-server' , [ 'gulp:styleguide-generate', 'gulp:styleguide-applystyles', 'watch' ]);

**Comment by devonatdomandtom** [comment]
Thank you @kraftner ! That worked perfectly.
