### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by gisu** [SC5/sc5-styleguide#850]
Using 3.40.0 on Node 4.2.0

Everytime i use the Server from the Styleguide, i got the "Unexpected token <" Error three times. (vendor.js:1, app.js:1, socket.io.js:1)

I have used the Precompiled Option, also the final CSS File - also reduced the CSS to one documented Block. Everytime i got the Error (Chrome and Firefox).

```
gulp.task('styleguide', function() {

    return gulp.src(kittn.dist.css + pkg.cssFileName + '.css')
      .pipe(styleguide.generate({
        title: 'Styleguide for: '+pkg.name+' (v.'+pkg.version+')',
        server: true,
        rootPath: kittn.styleguide.rootPath,
        appRoot: kittn.styleguide.appRoot,
        overviewPath: 'readme.md'
      }))
      .pipe(styleguide.applyStyles())
      .pipe(gulp.dest(kittn.styleguide.rootPath));
});
```

When i deactivate the Server the Styleguide is working.

**Comment by brycehewett** [comment]
What was the resolution to this. I'm getting the same error on app.js as well as a directive that I added.
