### ISSUE TITLE
applystyles does not work correctly

### ISSUE THREAD

**Issue by bechtold** [SC5/sc5-styleguide#867]
Hi,
I have a grunt workflow which I setup according to the docs.
Everything is working on the initial run, but once a file change happens and the compass and then gulp stuff is run again by the watch task the new styles don't get applied somehow.
So at the moment whenever I want to recreate the styleguide I have to stop grunt, run it again and then I get my changes. But I guess with the watch tasks this should not be needed.

So here are the important parts of my setup:

```
    gulp: {
      'styleguide-generate': function () {
        var outputPath = 'output';
        return gulp.src(['scss/*.scss'])
          .pipe(styleguide.generate({
            title: 'My first sc5 Styleguide',
            server: true,
            port: 2000,
            rootPath: outputPath,
            overviewPath : 'r.md'
          }))
          .pipe(gulp.dest(outputPath));
      },
      'styleguide-applystyles': function () {
        gulp.src('css/main.css')
          .pipe(styleguide.applyStyles())
          .pipe(gulp.dest('output'));
      }
    },

    watch: {
      scss: {
        files: '**/*.scss',
        tasks: ['sass', 'gulp:styleguide-generate', 'gulp:styleguide-applystyles']
      }
    }
```
```
  grunt.registerTask('default', ['sass', 'gulp:styleguide-generate', 'gulp:styleguide-applystyles', 'watch']);
```

So when I first run the default task:
![bildschirmfoto 2015-12-22 um 12 31 37](https://cloud.githubusercontent.com/assets/1275950/11954353/2406c1ae-a8a8-11e5-9e0e-0fbd38e84edf.png)

When a file change happens:
![bildschirmfoto 2015-12-22 um 12 33 45](https://cloud.githubusercontent.com/assets/1275950/11954381/4f2da7c6-a8a8-11e5-9171-8083f9d9cc4c.png)

So for the file change everything looks fine, but my new styles don't get applied. As I said when I kill grunt and run the default tasks again everything works fine. I know there is a message about the port already open by the generate task. But even if I remove the generate task from the file watcher the styles still don't get applied, so I don't think this is part of the problem. I checked the css file that gets copied to the output manually, it just does not change at all when watch runs the applystyles tasks.

Any idea why the applying of the styles might be broken?

**Comment by bechtold** [comment]
Trying more stuff to narrow down the problem.
When I run [clean](https://github.com/gruntjs/grunt-contrib-clean) on file changes before the gulp stuff the style guide gets generated as expected but none of the styles get applied. So it really is the apply task.

**Comment by topherauyeung** [comment]
This is also occurring in my gulp workflow. I also have to kill the task and re-run gulp to correctly generate the styleguide. :(

**Comment by bechtold** [comment]
Since @topherauyeung has the problems with gulp I renamed the issue.

Somehow it is working now in one project, even though I didn't change anything.
So from my point of view we could close the issue.

**Comment by bruvvn** [comment]
In my current project i run in the same issues like @bechtold.
I use grunt-gulp bridge. With grunt watch task the `styleguide.generate()` of `gulp:styleguide-generate task` try to start another instance of the server.
