### ISSUE TITLE
Default component isn't rendering

### ISSUE THREAD

**Issue by topherauyeung** [SC5/sc5-styleguide#874]
When the styleguide generates, it omits the base/default component in each section. For example - for my text fields, I have this documentation:

    // Text Field
    //
    // For when the user needs to input some freeform text.
    //
    // Markup: _text-field.html
    //
    // :disabled - When the field is uneditable.
    //
    // Styleguide 2.1```

The resulting documentation ONLY shows the disabled state and not the default state of the text field. For reference, here is the markup in `_text-field.html`:

    <label class="form--label" for="id">Last Name <span class="form--label-required">*</span></label>
    <input type="text" name="name" value="" class="form--textfield {$modifiers}" id="id" dir="auto" aria-label="Last Name" aria-required="true" required="">

Unrelated question: why is the syntax for including modifier classes different than what exists in kss-node? Seems like a completely unnecessary change, and it took me like half an hour to figure out what was wrong, because it's not well-documented.

**Comment by roderickmorales** [comment]
@topherauyeung How did you get it run using your source files? I have issue #872 open but it sounds you got a little further than me :) any help would be greatly appreciated.

Thanks!

**Comment by topherauyeung** [comment]
@roderickmorales Not sure how much help I'll be - I used the gulp plugin and got it up and running fairly quickly. Have you tried using it?

**Comment by varya** [comment]
You should have the default modifier, so instead of

```
// :disabled - When the field is uneditable.
```

write this:
```
// default  - Default
// :disabled - When the field is uneditable.
```

Please, let me know if it works for you.

**Comment by bruvvn** [comment]
thx @varya that works for me
