### ISSUE TITLE
Parse Sass @for loop

### ISSUE THREAD

**Issue by dsln** [SC5/sc5-styleguide#908]
I am attempting to create KSS markup with a grid system (e.g. `<div class="grid-##">Test</div>` where '##' is some number). The scss file includes a @for to generate each of the possible grid ##'s. When I try to run the gulp tasks, I get an 'undefined' and failed styleguide creation. What am I doing wrong?

e.g.
// Grid
//
// This is a grid
//
// markup:
// `<div class="grid border">`
// `<div class="flex">`
// `<span class='grid-25'>Hello</span>`
// `</div>`
// `</div>`
//
// Styleguide 1.0

... other scss here

@for $i from 1 through 40 {
.grid-#{$i} {
display:flex;
flex: 0 0 $large-square * $i;
}
}

**Comment by sascha-egerer** [comment]
Try to use the current master and you should see a more specific errror notice

**Comment by MatthieuScarset** [comment]
I'm interested in knowing what the issue is.
@dsln could you post the debug when you found it?

**Comment by dsln** [comment]
Unfortunately our team moved away from SC5 and made our own solution - I will not be able to reproduce.  Closing the issue.

**Comment by MatthieuScarset** [comment]
Ok. Thank you anyway ;)
