### ISSUE TITLE
Menu items not showing up

### ISSUE THREAD

**Issue by shainanigans** [SC5/sc5-styleguide#914]
I've reviewed the demo structure and KSS and can't work out why the menu items are not showing up on my own styleguide. After serving the page, I only see the "Overview" menu item.

(Relevant) Folder Structure:
- Project Folder
    - dist
    - node_modules
    - src
        - includes
            - sass
                - components
                - master.scss
    - styleguide
    - gulpfile.js
    - package.json
    - README.md

Gulp Task:
```
// generate Styleguide
var styleguide = require('sc5-styleguide');
var outputPath = 'styleguide';
gulp.task('styleguide:generate', function() {
  return gulp.src('*.scss')
	.pipe(styleguide.generate({
		title: 'Boilerplate Styleguide',
		server: true,
		rootPath: outputPath,
		overviewPath: 'README.md'
	  }))
	.pipe(gulp.dest(outputPath));
});


// apply styles
gulp.task('styleguide:applystyles', function() {
  return gulp.src('master.scss')
	.pipe(sass({
	  errLogToConsole: true
	}))
	.pipe(styleguide.applyStyles())
	.pipe(gulp.dest(outputPath));
});
```
Relevant section of `master.scss` that I'm using for testing the styleguide:
```
@import "components/typography";
```

Part of `_typography.scss` that I'm using for testing:
```
/*
Colors and typography
This section describes base colors and typography
Styleguide 1.0
*/

/*
Links

Normal links.

markup:
<a>This is a link</a>

Styleguide 1.1
*/

a {
	@include transition(all 0.2s ease-in-out);
	color: $link-color;
	text-decoration: none;
	&:hover {
		color: $link-hover-color;
		text-decoration: underline;
	}
	&:focus {
		color: $link-hover-color;
		outline: 1px dotted $link-color;
	}
}
```

Is this user error... or something else? (Either way, advice appreciated!)

**Comment by varya** [comment]
The path you provide to as a gulp source is looking for `*.scss` files **in the root of your project**, and there is nothing there.
BTW, next time try to ask at [StackOverflow](http://stackoverflow.com/). There is a lot of developers there ready to help, so you will get an answer for basic questions much sooner.
