### ISSUE TITLE
Please check validity of the block starting from line #22

### ISSUE THREAD

**Issue by hans2103** [SC5/sc5-styleguide#939]
When I run `grunt gulp:styleguide-generate` I get the following reply. 

```
$ grunt gulp:styleguide-generate
Running "gulp:styleguide-generate" (gulp) task
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
Please check validity of the block starting from line #22

Done.


Execution Time (2016-05-10 11:01:09 UTC)
loading tasks             605ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 54%
loading grunt-gulp         16ms  ▇▇▇ 1%
gulp:styleguide-generate  495ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 44%
Total 1.1s
```

What does the reply mean with `Please check validity of the block starting from line #22`?
What block from which file should I check?

**Comment by varya** [comment]
Please provide the CSS (SASS, LESS) code on which you run the tool and the grunt task where you use the sc5-styleguide. Link to the repo will also work.

**Comment by hans2103** [comment]
repo is private and sass contains of many files.
Therefor it would be cool if the error message would contain the file name.
Now it only contains the line number where the error occurs.

**Comment by Ampersandman** [comment]
Had the same problem.
Found the cause to be a sass variable followed by a number as classname:
```
.#{$prefix}-2x {
}
```

**Comment by hans2103** [comment]
Can the error reporting be adjusted including filename?

**Comment by Ensaphelon** [comment]
An error `Please check validity of the block starting from line #111` occurs when there is such a substring in my .less file
`when not (@_actions-toolbar-actions-position = justify)`
