### ISSUE TITLE
Hide Markup by default

### ISSUE THREAD

**Issue by Grienauer** [SC5/sc5-styleguide#981]
Is there a way to show the ".sg-code-listing" / Markup Region by default as closed?
Now it is open by default, but I would prefer to only show it closed by default.

**Comment by jameelmoses** [comment]
+1

**Comment by PhilippeVay** [comment]
Searching for [showMarkup](https://github.com/SC5/sc5-styleguide/search?utf8=%E2%9C%93&q=showMarkup) gives interesting results like [section.js](https://github.com/SC5/sc5-styleguide/blob/c42a2c9cd2012bc86208dd9e4f56a7f5c87d1182/lib/app/js/directives/section.js#L27-L30) but I fail to see if this setting can be overridden from the build task or if a directive is needed...

**Comment by Grienauer** [comment]
I know, this is not an urgent and really minor issue, but could you tell us if there is/will be any progress on this?

**Comment by junaidrsd** [comment]
showMarkupSection option added to the recent release and markup section is open default. But it can be set to false to make markup section close.
