### ISSUE TITLE
Running styleguide from site's local server

### ISSUE THREAD

**Issue by shainanigans** [SC5/sc5-styleguide#990]
Hi,
I've reread [this issue](https://github.com/SC5/sc5-styleguide/issues/779) and @varya 's [advice on using the appRoot parameter](http://varya.me/en/posts/sc5-styleguide-for-smallers/#providing-the-approot-parameter-) when running the styleguide from the site's local server (rather than running it on its own server, which does work for me) but localserver:3000/styleguide is loading a blank page. I'm running my server through browsersync.

The console shows that that the browser is looking for the styleguide files at the root, rather than in the `styleguide` folder:
```
GET http://localhost:3000/js/vendor.js 
(index):26 GET http://localhost:3000/styleguide-app.css addCssLink @ (index):26(anonymous
function) @ (index):35(anonymous function) @ (index):36
(index):59 GET http://localhost:3000/js/app.js 
(index):26 GET http://localhost:3000/styleguide_at_rules.css addCssLink @ (index):26(anonymous
function) @ (index):34(anonymous function) @ (index):36
(index):60 GET http://localhost:3000/socket.io/socket.io.js 404 (Not Found)
```
My (relevant) folder structure:
```
dist
--website
----styleguide
src
gulpfile.js
STYLEGUIDE.md
```

My gulp file:
```
var styleSourcePath = 'src/assets/scss';
var scssRoot = styleSourcePath + '/master.scss';
var styleguidePath = 'dist/website/styleguide';

gulp.task('styleguide:generate', function() {
	return gulp.src([
		styleSourcePath + '/components/*.scss',
		styleSourcePath + '/helpers/*.scss',
		styleSourcePath + '/layout/*.scss',
		styleSourcePath + '/print/*.scss',
		styleSourcePath + '/sections/*.scss',
		styleSourcePath + '/vendor/*.scss',
	])
	.pipe(styleguide.generate({
		title: 'Styleguide',
		rootPath: styleguidePath,
		appRoot: '/styleguide',
		overviewPath: 'STYLEGUIDE.md',
		customColors: 'src/assets/scss/vendor/_styleguide-overrides.css'
	}))
	.pipe(gulp.dest(styleguidePath));
});

gulp.task('styleguide:applystyles', function() {
	return gulp.src(scssRoot)
	.pipe($.sass({
		errLogToConsole: true
	}))
	.pipe(styleguide.applyStyles())
	.pipe(gulp.dest(styleguidePath));
});

gulp.task('watchstyles', ['styleguide'], function() {
	gulp.watch(['*.scss'], ['styleguide']);
});
```

Where have I gone wrong?

**Comment by junaidrsd** [comment]
try this
`appRoot: '/dist/website/styleguide',`

**Comment by shainanigans** [comment]
I ended up deleting the existing styleguide folder and starting almost from scratch (though the gulp task above stayed the same), and it worked. Still not sure what the issue was.

One thing I did notice is that the `appRoot` needs to be `/styleguide` not just `styleguide`. It's not very clear on the README.
