### ISSUE TITLE
Hide full screen button

### ISSUE THREAD

**Issue by meriturva** [SC5/sc5-styleguide#999]
Any configuration to hide full screen function?

I just would like to hide html part:

`<a ui-sref="app.fullscreen({section: '1.3'})" target="_blank" href="#/section/1.3/fullscreen">
        <i class="fa fa-arrows-alt"></i>
      </a>`

Thanks!

**Comment by PhilippeVay** [comment]
In CSS, you can hide these links with `.sg.label > a[href$="/fullscreen"] { display: none }` (the first part needed for specificity reasons: it should override `.sg.label a { display: inline-block; }`)

Link is still into HTML code and SC5 will still display the same view if you append `/fullscreen` to the URL of any component. To get rid of this you have to modify a view or app.js

**Comment by varya** [comment]
We cannot make a configuration option for every single UI element. This way the list of option will grow huge. So I support the advice of @PhilippeVay. Do you CSS to overwrite the visibility of the link. Hope this will help.
